# -*- coding: utf-8 -*-
"""Route.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GN_ZMNsRLgloPvPx48vgFVG7NJ_vE54
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('routeF.csv')
X = df.iloc[:, 2:6].values
y = df.iloc[:, 1].values
df.head()

# corr = df.corr()
# ax1 = sns.heatmap(corr, cbar=0, linewidths=2,vmax=1, vmin=0, square=True, cmap='Blues')
# plt.show()

# df.info()

# print(X[1])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 1)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

temp = list(regressor.coef_)
temp.append(regressor.predict([[0,0,0,0]])[0])

print(*temp)